"""
error file for all class for Invoices


"""


class InvoiceError(Exception):
    """%s"""
    def __init__(self, msg=""):
        super().__init__(self.__doc__ % msg)


class NotAVyaparPDF(InvoiceError):
    """The PDF %s provided is not generated by Vyapar app """


class VyaparPDFReadError(InvoiceError):
    """%s"""


class InvalidGstType(InvoiceError):
    """GST can be either CGST or SGST %s """


class RateChangeError(InvoiceError):
    """Cannot change rate once assigned %s """


class GstAmountChangeError(InvoiceError):
    """Cannot change amount once assigned %s """


class GSTBaseInsufficientArgs(InvoiceError):
    """type, rate and sub_total/amount is required %s """


class IncorrectGSTRates(InvoiceError):
    """CGST and SGST rates should be equal %s """


class GSTChangeError(InvoiceError):
    """Cannot change GST once assigned %s """


class GSTInsufficientArgs(InvoiceError):
    """parameters are not sufficient either cgst and sgst should be passed or rate, sub_total should be passed %s"""
